### ISSUE TITLE
Workflows are referencing vulnerable actions

### ISSUE THREAD

**Issue by igibek** [leojackson/PsLogLite#37]
Hello, there! 

As part of the university research we are currently doing regarding the security of Github Actions, we noticed that one or many of the workflows that are part of this repository are referencing vulnerable versions of the third-party actions. As part of a disclosure process, we decided to open issues to notify GitHub Community. 

*Please note that there are could be some false positives in our methodology, thus not all of the open issues could be valid. If that is the case, please let us know, so that we can improve on our approach. You can contact me directly using an email: ikoishy [at] ncsu.edu* 

Thanks in advance
1. The workflow **publish.yml** is referencing action **gittools/actions/gitreleasemanager/setup** using references **v0.9.2**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.
1. The workflow **publish.yml** is referencing action **gittools/actions/gitreleasemanager/close** using references **v0.9.2**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.
1. The workflow **release.yml** is referencing action **gittools/actions/gitversion/setup** using references **v0.9.2**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.
1. The workflow **release.yml** is referencing action **gittools/actions/gitversion/execute** using references **v0.9.2**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.
1. The workflow **release.yml** is referencing action **gittools/actions/gitreleasemanager/setup** using references **v0.9.2**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.
1. The workflow **release.yml** is referencing action **gittools/actions/gitreleasemanager/create** using references **v0.9.2**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.

The vulnerability fix that is missing by actions' versions could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider updating the reference to the action. 

*If you end up updating the reference, please let us know. We need the stats for the paper :-)*

**Comment by leojackson** [comment]
Thank you for the disclosure. I'm updating the files in question, and once they're tested I'll push to master.

**Comment by leojackson** [comment]
Build failed, reopening until it succeeds

**Comment by leojackson** [comment]
@igibek - Thank you again for reporting this vulnerability. I won't be issuing a new version of PsLogLite, as the code of the module itself was not modified, but everything is working in the CI/CD pipeline.
